### PR TITLE
Update dependencies automatically with Release Hub Gradle Plugin

### PR DESCRIPTION
**Pull request by diklimchuk**
This merge request adds support for automatic dependencies updates using [Releases Hub Gradle Plugin](https://github.com/dipien/releases-hub-gradle-plugin)

This plugin will automatically update dependencies in the source code and create pull requests with changes. [Here](https://github.com/diklimchuk/elmslie/pulls) is an example of what it will look like.

Dependencies are now kept together with versions and will be edited automatically by the plugin. Updates will run twice a month or by a manual request

### CODE REVIEW

**Comment by opengamer29** [comment]
That's a cool feature, but Are you sure that we have enough tests for auto-updating dependencies, especially Android tests?

**Comment by diklimchuk** [comment]
> That's a cool feature, but Are you sure that we have enough tests for auto-updating dependencies, especially Android tests?

There are no tests for now, but i wanted to add them in future. I guess tests are not a problem, since mr still will be merged manually. If there will be any necessary changes they can be added to the mr with version updates. If some bugs with dependency udpate won't be found in review they can still be tracked in the app's testing cycle. This is similar to updating any other dependencies in the vivid.money app. Dependencies are updated manually and the rest of responsibility is on the QA team

**Comment by opengamer29** [comment]
> > That's a cool feature, but Are you sure that we have enough tests for auto-updating dependencies, especially Android tests?
> 
> There are no tests for now, but i wanted to add them in future. I guess tests are not a problem, since mr still will be merged manually. If there will be any necessary changes they can be added to the mr with version updates. If some bugs with dependency udpate won't be found in review they can still be tracked in the app's testing cycle. This is similar to updating any other dependencies in the vivid.money app. Dependencies are updated manually and the rest of responsibility is on the QA team

Got it. Works for me.

**Review by opengamer29 — APPROVED** [review]

**Comment by diklimchuk** [comment]
@sergei-lapin Could you please take a look at this? I suppose it would be better, since this pull request is in the area of your competence

**Review by sergei-lapin — APPROVED** [review]

**Pull request merged**
